# -*- coding: utf-8 -*-
"""HyperParam_Opt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZIE591KPMaSLie-ZP9ucE6Tq3LM8_Rtb
"""

import numpy as np
import pandas as pd

from sklearn import ensemble
from sklearn import metrics
from sklearn import model_selection
from sklearn import decomposition
from sklearn import preprocessing
from sklearn import pipeline


df = pd.read_csv("/content/train.csv")
X = df.drop("price_range", axis = 1).values
y = df.price_range.values

classifier = ensemble.RandomForestClassifier(n_jobs = -1)
param_grid = {
    "n_estimators" : [100, 200, 500, 1000],
    "max_depth" : [3, 5, 7],
    "criterion" : ["gini", "entropy"]
    }

model = model_selection.GridSearchCV(
    estimator=classifier,
    param_grid=param_grid,
    scoring="accuracy",
    verbose = 10,
    n_jobs = 1,
    cv = 5
    )

model.fit(X, y)

print(model.best_score_)
print(model.best_estimator_.get_params())

classifier = ensemble.RandomForestClassifier(n_jobs = -1)
param_grid = {
    "n_estimators" : np.arange(100, 1500, 100),
    "max_depth" : np.arange(1, 20),
    "criterion" : ["gini", "entropy"]
    }

model = model_selection.RandomizedSearchCV(
    estimator=classifier,
    param_distributions=param_grid,
    scoring="accuracy",
    n_iter = 10,
    verbose = 10,
    n_jobs = 1,
    cv = 5
    )

model.fit(X, y)

print(model.best_score_)
print(model.best_estimator_.get_params())

